version: "3"

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    network_mode: host
    volumes:
      - $HOME/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $HOME/caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: $USER
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "/var/run/postgresql:/var/run/postgresql"
      - "db_data:/var/lib/postgresql/data"
  redis:
    image: redis:6
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
  elastic:
    image: boldpenguin/opensearch:latest
    restart: unless-stopped
    environment:
      discovery.type: single-node
    volumes:
      - "es_data:/usr/share/opensearch/data"
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9600:9600"
  selenium:
    image: selenium/standalone-chrome:3.141.59-20210713
    restart: unless-stopped
    volumes:
      - "/dev/shm:/dev/shm"
    ports:
      - "127.0.0.1:4444:4444"
  singularity:
    image: quay.io/singularity/singularity:v3.8.3
    privileged: true
    working_dir: "/data"
    volumes:
      - "$PWD:/data"
      - "$HOME/.singularity:/root/.singularity"
  abinit:
    image: jmbeuken/abinit:9.6.2
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/abinit-9.6.2/bin:/opt/libxc-4.3.4/bin
    working_dir: "/data"
    volumes:
      - "$PWD:/data"

volumes:
  db_data:
    driver: local
  es_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
